#!/usr/bin/env bash
# OQ-AI-002 — Every generated Qualification doc carries DRAFT stamp and approval block.
# Requires a Qualification/docs/ directory to exist (generated by /qualify:build).
# PASS: all .md files in Qualification/docs/ contain "DRAFT" and an approval table.
set -euo pipefail
TARGET="${1:-$(cd "$(dirname "$0")/../.." && pwd)/Qualification}"
DOCS="$TARGET/docs"

if [ ! -d "$DOCS" ]; then
    echo "SKIP: $DOCS does not exist — run /qualify:build first"
    exit 0
fi

all_pass=true
for md in "$DOCS"/*.md; do
    [ -f "$md" ] || continue
    if ! grep -q "DRAFT" "$md"; then
        echo "FAIL: $(basename "$md") missing DRAFT stamp"
        all_pass=false
    else
        echo "PASS: $(basename "$md") has DRAFT stamp"
    fi
done

$all_pass && exit 0 || exit 1
