#!/usr/bin/env python3
"""build_catalog.py — regenerate the catalog in docs/OVERVIEW.md from the repo itself,
so the inventory of commands / skills / sub-agents never drifts from what's installed.

Run after adding, renaming, or removing a command, skill, or agent:
    python3 docs/build_catalog.py

It reads the `description:` frontmatter of every command (commands/**/*.md), skill
(skills/*/SKILL.md), and sub-agent (agents/*.md) and rewrites the block between the
<!-- CATALOG:START --> / <!-- CATALOG:END --> markers in docs/OVERVIEW.md.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OVERVIEW = ROOT / "docs" / "OVERVIEW.md"
START, END = "<!-- CATALOG:START -->", "<!-- CATALOG:END -->"


def description(md: Path) -> str:
    """Pull the `description:` out of a file's YAML frontmatter (handles folded `>-`)."""
    t = md.read_text(encoding="utf-8")
    if not t.startswith("---"):
        return ""
    end = t.find("\n---", 3)
    fm = t[3:end] if end != -1 else t[3:]
    lines = fm.splitlines()
    for i, ln in enumerate(lines):
        m = re.match(r"\s*description:\s*(.*)$", ln)
        if not m:
            continue
        val = m.group(1).strip()
        if val in (">", ">-", "|", "|-"):           # folded / literal block scalar
            out = []
            for cont in lines[i + 1:]:
                if re.match(r"\s+\S", cont):          # indented continuation line
                    out.append(cont.strip())
                else:
                    break
            return " ".join(out)
        return val.strip().strip('"').strip("'")
    return ""


def esc(s: str) -> str:
    return s.replace("|", "\\|")


def commands():
    base = ROOT / "commands"
    fams = {}
    for md in sorted(base.rglob("*.md")):
        rel = md.relative_to(base)
        if len(rel.parts) == 1:
            fam, inv = "(top-level)", f"/{md.stem}"
        else:
            fam, inv = rel.parts[0], f"/{rel.parts[0]}:{md.stem}"
        fams.setdefault(fam, []).append((inv, description(md)))
    return fams


def simple(base_glob):
    base = ROOT / base_glob
    return base


def render() -> str:
    out = [
        "## Catalog",
        "",
        "_Auto-generated by `docs/build_catalog.py` from the repo — do not hand-edit "
        "between the CATALOG markers; re-run the script instead._",
        "",
        "### Commands (you type these)",
        "",
    ]
    fams = commands()
    for fam in sorted(fams):
        out += [f"**{fam}**", "", "| Command | What it does |", "|---|---|"]
        for inv, desc in fams[fam]:
            out.append(f"| `{inv}` | {esc(desc)} |")
        out.append("")

    out += ["### Skills (Claude invokes these automatically)", "",
            "| Skill | What it does |", "|---|---|"]
    for sk in sorted((ROOT / "skills").glob("*/SKILL.md")):
        out.append(f"| `{sk.parent.name}` | {esc(description(sk))} |")
    out.append("")

    out += ["### Sub-agents (run in parallel by `/qualify:build` and `/qualify:review`)", "",
            "| Sub-agent | What it does |", "|---|---|"]
    for md in sorted((ROOT / "agents").glob("*.md")):
        out.append(f"| `{md.stem}` | {esc(description(md))} |")
    out.append("")
    return "\n".join(out)


def main():
    block = f"{START}\n{render()}\n{END}"
    text = OVERVIEW.read_text(encoding="utf-8")
    if START in text and END in text:
        text = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    OVERVIEW.write_text(text, encoding="utf-8")
    print("catalog regenerated in docs/OVERVIEW.md")


if __name__ == "__main__":
    main()
